arawa/workspace

.github/dependabot.yml
StCyr cannot work on this subject. I take the reins.
=> build(dependabot): Change of user to be assigned for all changes on npm

.github/workflows/makefile.yml, package-lock.json
I removed the configure line because, I don't use a configure file.
=> Fix the make in the CI

CHANGELOG.md
I added a new feature : new Czech translation
- commit link 1 : https://github.com/arawa/workspace/pull/541
- commit link 2 : https://github.com/arawa/workspace/pull/542
=> chore(): Update the CHANGELOG.md

CHANGELOG.md, appinfo/info.xml, appinfo/routes.php, src/Home.vue
I commented the convert/import feature.
We will think how to use this feature, but, for the moment, we will hide for the user.
=> revert: Comment the convert feature

README.md, appinfo/info.xml
Change the Groupfolders' release advice for the v9.1.1 .
=> docs(README,info): Change the GF's release advise

CHANGELOG.md
I added the PR on the refactoring create workspace in the CHANGELOG.md file.
=> Add the PR refactoring create workspace

CHANGELOG.md, lib/Controller/WorkspaceController.php, lib/Service/WorkspaceService.php
I limited the user search if the "Restrict users to only share with users in their groups" option from Settings > Share is checked.
=> Limiting user search

CHANGELOG.md, appinfo/info.xml
=> chore():Release to v1.3.0 and update the CHANGELOG

lib/Controller/GroupController.php, src/SelectGroupfolders.vue, src/store/actions.js, src/store/mutations.js
I fixed the deleting of the group for a goupfolder converted in a workspace.
I added all users from advanced permissions to the WorkspacesManagers group.
I fixed the width of the modal of the SelectGroupfolders.vue.
=> fix(): Delete group and change style for the modal

CHANGELOG.md, lib/Service/Workspace/WorkspaceCheckService.php
=> Fix the pattern to check special char

.editorconfig
I created the .editorconfigfile file to maintain a code style.
=> Init the .editorconfig file

CHANGELOG.md
I added the PRs on the coding standard and the .editorconfig. I also added the PR on the fix for npm test.
=> Add 3 PRs in the CHANGELOG.md file

CHANGELOG.md, composer.json, composer.lock
I defined that we must use between 7.4 and 8.1 of PHP.
=> chore(): Add informations about the release PHP

CHANGELOG.md, lib/Controller/GroupController.php, lib/Controller/WorkspaceController.php, lib/Migration/RegisterWorkspaceUsersGroup.php, lib/Service/UserService.php, lib/Service/WorkspaceService.php, tests/Unit/Service/UserServiceTest.php
I replaced ILogger by LoggerInterface to be compliant with PSR-3.
=> Replace ILogger by LoggerInterface

src/Home.vue
I filtered the groupfolderId constant to get the Groupfolder's ID.
=> fix(vue): Filter the groupfolderId

src/GroupDetails.vue, src/SpaceDetails.vue
I changed the index when we want to get the value via an event.
=> Change the index from Nextcloud 25

src/GroupDetails.vue, src/SpaceDetails.vue
I changed the index when we want to get the value via an event.
=> fix(Vue): Change the index from Nextcloud 25

CHANGELOG.md
This change is for the future stable26 branch.
=> chore(): Update the changelog for the main

.github/workflows/makefile.yml, .github/workflows/node.js.yml, .github/workflows/php.yml
I added "stable*" to trigger our CI when we will create a PR for main, stable24 and stable25.
=> build(workflow): Add stable*

appinfo/info.xml
=> Backport: Update groupfolder to 9.2 in the info.xml for NC24

CHANGELOG.md, appinfo/info.xml
=> chore(): Update the Changelog and release to 1.3.2

appinfo/routes.php, src/Home.vue
We disable this feature for Workspace v1.3.2 and we will re-enable from nextcloud25 or nextcloud26.
=> Disable the conversion feature

CHANGELOG.md, appinfo/routes.php, src/Home.vue
=> Backport: Disable the conversion feature - stable25

CHANGELOG.md, appinfo/routes.php, src/Home.vue
=> Backport : Disable the conversion feature stable24

.github/workflows/php.yml
=> build(workflow): Change stable21 to stable25

.github/workflows/php.yml
=> backport - Change stable21 to stable25

appinfo/info.xml
=> chore(): Update the release to 2.0.0 for stable25

README.md, appinfo/info.xml
I updated the info.xml and README.md for more instructions to configure groupfolders from Nextcloud 25.
=> Update instructions for stable25

composer.lock, package-lock.json
=> chore():Update package-lock.json and composer.lock

README.md, appinfo/info.xml
Correction of mistakes or complex sentences.
=> chore(): Update the README and info.xml

lib/Db/SpaceMapper.php
I defined a parameter for the spacename variable.
It resolved a problem for the SQL Injection.
=> Define a parameter for the spacename var

CHANGELOG.md
I added the Pull Request to fix the problem about the SQL Injection.
=> chore(): Update the Changelog

README.md, appinfo/info.xml
I updated about the new release Groupfolders to v9.2.1.
=> chore(): Update comments about the new release GF

README.md, appinfo/info.xml
I updated about the new release Groupfolders to v9.2.1.
=> Backport: Update comments about the new release GF

CHANGELOG.md, lib/Controller/GroupController.php, lib/Controller/SpaceController.php, lib/Controller/WorkspaceController.php
enable CSRF protection in WorkspaceController, SpaceControllers and GroupControllers
=> chore(controller): remove @NoCSRFRequired tokens

CHANGELOG.md
I forgot to add information on Pull Request for the release 2.0.0.
=> Add release 2.0.0

CHANGELOG.md
I moved one line in the CHANGELOG.md file to the Unreleased > Chore section.
=> Move one line changelog

CHANGELOG.md, appinfo/info.xml
@acdmft Can you review my changes, please ? :pray:
=> Update the release for stable24 to v1.3.3

CHANGELOG.md, appinfo/info.xml
Hi @acdmft :wave:
Can you review my changes , please ? :pray:
=> Update the release for stable25 to v2.0.1

.github/workflows/semgrep.yml
I followed this documentation :
https://semgrep.dev/docs/semgrep-ci/sample-ci-configs/#github-actions .
=> build(CI): Init Semgrep for the Workspace app

l10n/cs.js, l10n/cs.json, l10n/en.js, l10n/fr.js, l10n/fr.json, src/SpaceDetails.vue, src/services/groupfoldersService.js, src/tests/unit/groupfoldersService.test.js
I fixed an issue that when you rename a space that already exists.
The existing one is "deleting".
=> Prevent duplicate spacename rename

src/tests/jest.setup.js
I resolved an issue around the console.debug or console.error.
Example :
```bash
npm test
> workspace@1.0.0 test
> jest
PASS  src/tests/unit/spaceService.test.js
transferUsersToUserGroup method
✓ Return object type (6 ms)
✓ Is not undefined (2 ms)
PASS  src/tests/unit/groupfoldersService.test.js
getAll function
✓ calls axios.get method (7 ms)
✓ returns data value of the object if resp status is ok (8 ms)
✓ throws error if resp status is not ok (85 ms)
get function
✓ calls axios.get method (1 ms)
✓ returns data property of the object if response status is ok (1 ms)
✓ throws exception if response status is not ok (5 ms)
formatGroups function
✓ calls axios.post method (1 ms)
✓ returns entire object received from axios.post (1 ms)
formatUsers function
✓ calls axios.post method (6 ms)
✓ …
```
=> test(): Silent all errors around console in js

lib/Controller/GroupController.php
I didn't know why I added pluses instead of dots to concate strings...
=> Replace the plus by a dot

.github/workflows/lint-eslint.yml, src/Errors/Groupfolders/AddGroupToGroupfolderError.js, src/Errors/Groupfolders/EnableAclGroupfolderError.js, src/Home.vue, src/main.js, src/router.js, src/services/Notifications/NotificationError.js, src/services/groupfoldersService.js, src/services/spaceService.js, src/store/actions.js, src/store/getters.js, src/store/index.js, src/store/mutations.js, src/tests/__mocks__/axios.js, src/tests/jest.setup.js, src/tests/unit/groupfoldersService.test.js, src/tests/unit/selectUsers.test.js, src/tests/unit/store.test.js
added a workflow that runs ESLint each time the new code is pushed on github or new PR is created
=> build(CI): add lint-eslint.yml file

l10n/en.js, l10n/fr.js, l10n/fr.json, src/RemoveSpace.vue, src/SpaceDetails.vue
Hi @acdmft ! :wave: 
Can you review this backport for Nextcloud 25, please ?
Hey @dorianne-arawa :wave:
=> Backport/del space ncmodal/774/stable25

Makefile
I added the package-lock.json and composer.lock files to remove.
Add the js folder to remove when we use the fullclean make command.
=> Change fullclean command

lib/Controller/GroupController.php, lib/Controller/PageController.php, lib/Controller/SpaceController.php, lib/Controller/WorkspaceController.php, lib/Db/Space.php, lib/Db/SpaceMapper.php, lib/Exceptions/BadRequestException.php, lib/Middleware/IsGeneralManagerMiddleware.php, lib/Middleware/IsSpaceAdminMiddleware.php, lib/Middleware/WorkspaceAccessControlMiddleware.php, lib/Migration/RegisterWorkspaceUsersGroup.php, lib/Service/Group/GroupFormatter.php, lib/Service/Group/GroupsWorkspaceService.php, lib/Service/SpaceService.php, lib/Service/User/UserFormatter.php, lib/Service/User/UserWorkspace.php, lib/Service/UserService.php, lib/Service/Workspace/WorkspaceCheckService.php, lib/Service/WorkspaceService.php, tests/Integration/AppTest.php, tests/Unit/Middleware/WorkspaceAccessControlMiddlewareTest.php, tests/Unit/Service/UserServiceTest.php
@acdmft can you review my code, please ? :pray: 
:warning: **Attention** ! Don't accept this PR for the moment. I would like to test it on a Nextcloud 25 and 26.
=> Refactor to be compatible with php8.0

CHANGELOG.md, docs/dev/CHANGELOG.md, src/SpaceDetails.vue
It's a patch from the PR #838 for the stable3.0 branch.
=> Fix/remove space issue/stable3.0

CHANGELOG.md, lib/AppInfo/Application.php, lib/Migration/ChangeGroupnamesV300.php
I moved the V300 constant to changeGroupnamesv300.
=> fix(php): Move the V300 constant

CHANGELOG.md, lib/AppInfo/Application.php, lib/Migration/ChangeGroupnamesV300.php
It's a patch for the stable3.0 branch based on this PR : https://github.com/arawa/workspace/pull/841
@acdmft can you review my PR, please ?
=> Fix/move v300 constant/stable3.0

CHANGELOG.md, lib/Upgrade/UpgradeV300.php
Instead of sorting by virtual groups, I sorted by the group that interested me.
=> Get SPACE-GE and SPACE-U groups only

CHANGELOG.md, docs/dev/CHANGELOG.md
=> chore(): Update the changelog for the next release

CHANGELOG.md, appinfo/info.xml
This new release is compatible with NC27.
=> New Workspace 3.0.3 release

README.md, appinfo/info.xml
I added a Upgrade guideline > v3.0.4 sections in info.xml and README.md.
=> Add a Upgrade guideline section

CHANGELOG.md, appinfo/info.xml
=> Release to v3.0.4 and change the CHANGELOG

appinfo/routes.php, src/SelectUsers.vue
This feature is not yet complete.
@dorianne-arawa
=> Disable users import feature

CHANGELOG.md
Add these Pull Requests :
- https://github.com/arawa/workspace/pull/915
- https://github.com/arawa/workspace/pull/900
- https://github.com/arawa/workspace/pull/893
- https://github.com/arawa/workspace/pull/888
=> chore(CHANGELOG): Update the changelog

src/SelectUsers.vue
I removed a comment from css line that highlight users not members of a workspace.
It's a backport from #888
=> Backport: Apply the highlight for new members

appinfo/routes.php, lib/Controller/GroupController.php, lib/Controller/WorkspaceController.php, lib/Service/UserService.php, lib/Workspace/WorkspaceChecker.php, src/store/actions.js
I refactored the `removeUser()` function to simplify it.
=> Preventing accidental deletion of the SPACE-GE group

lib/Controller/GroupController.php
I forgot to add the @NoAdminRequired and @SpaceAdminRequired annotations.
=> A no admin user can remove user from a workspace

CHANGELOG.md
=> Added occ commands for creating and importing wokrspaces

css/workspace-style.css, package-lock.json, package.json, src/GroupDetails.vue, src/SpaceDetails.vue, src/SpaceMenuItem.vue
fix icon alignments, cursor permanent visibility and space between counters and cursor
=> fix workspace icon alignments

lib/Controller/WorkspaceController.php
We defined the added_groups key on the front-end side and now it's managed on the backend side.
=> Move the added_groups key on the backend side

src/MenuItemSelector.vue, src/SpaceMenuItem.vue
new component MenuItemSelector. Created for the Added Groups feature
=> MenuItemSelector

lib/Middleware/IsSpaceAdminMiddleware.php, src/store/actions.js
- actions with spaceId parameters in data
- fix @spaceamdinrequired
- fix also error message handling in front
=> [bug] Can't create workspace group

.github/workflows/makefile.yml
I updated to get errors with this ci.
=> ci: Update the version of PHP to 8.2

lib/Service/UserService.php
Should fix:
```
Error: Undefined array key "groups" at /var/www/nextcloud/apps/workspace/lib/Service/UserService.php#65
```
=> Ensure groups is an array before try to access them

appinfo/routes.php, lib/Controller/ConnectedGroupController.php, lib/Helper/GroupfolderHelper.php
Create a API to insert and remove connected groups.
- **verb**: POST
- **URI**: http://nextcloud.local/index.php/apps/workspace/spaces/:spaceId/connected-groups/:gid
- **Paramaters**:
- `:spaceId` : 1
- `:gid` : Robots 1
Response : 
```json
{
"message": "The Robots 1 group is added to the Espace01 workspace.",
"success": true
}
```
- **verb**: DELETE
- **URI**: http://nextcloud.local/index.php/apps/workspace/spaces/:spaceId/connected-groups/:gid
- **Paramaters**:
- `:spaceId` : 1
- `:gid` : Robots 1
```json
{
"message": "The Robots 1 group is removed to the Espace01 workspace.",
"success": true
}
```
OP#2928
=> Create api to insert and remove connected groups

l10n/en.js, l10n/fr.js, l10n/fr.json, src/SelectConnectedGroups.vue, src/SpaceDetails.vue
We can select groups and list them, then add them to the workspace.
For Arawa: OP#2926
=> Select groups to add them later

src/SelectConnectedGroups.vue
- glitch solved with "appendToBody"
- get a better "user/groups" display with "userSelect"
- use "loadingGroups" icon when necessary
=> fix: glitch on "add group dialog"

package.json, src/GroupMenuItem.vue, src/LeftSidebar.vue, src/SpaceMenuItem.vue
- Add "+" actions on Workspace Groups and Added Groups
- + Vue Warning : use name instead of title
=> + Actions on groups

README.md, appinfo/info.xml
Change the wording and delete the Upgrade guideline section.
=> Update the README.md and info.xml

CHANGELOG.md
=> chore: Fix wording in the changelog

appinfo/routes.php, lib/Controller/GroupController.php, lib/Space/SpaceManager.php, src/services/spaceService.js, src/store/actions.js
Fixes the issue where "Password confirmation is required" by allowing groups to be attached without needing password confirmation.
=> Backport: create api attach group to workspace - stable3.2

lib/Controller/GroupController.php, lib/Service/Group/GroupFormatter.php, lib/Service/Slugger.php, src/GroupDetails.vue, src/GroupMenuItem.vue, src/SelectUsers.vue, src/UserTable.vue, src/router.js, src/store/actions.js, src/tests/unit/selectUsers.test.js
We can add or create groups with slash in the URL without problem.
For example : "My-Group/01".
=> Create a slug system to encode resources for the URL

appinfo/info.xml
This release  is available for Nextcloud 30.
=> Create release 3.3.2

Makefile
This commit includes the CHANGELOG in the final artifact to provide users with a clear overview of changes in each version. instance.
Additionally, end-users will be able to view the CHANGELOG from their Nextcloud instance.
OP#3014
=> Include the CHANGELOG in the appstore

src/UserTable.vue
=> Ensure only subgroup users can be removed

lib/Exceptions/BadRequestException.php
=> Show error special characters when renaming a workspace

lib/Controller/GroupController.php, lib/Controller/WorkspaceController.php, lib/Group/Admin/AdminGroupManager.php, lib/Group/User/UserGroupManager.php, lib/Space/SpaceManager.php, tests/Unit/Space/SpaceManagerTest.php
Fix some error messages i met during investigating on workspace creation
=> fix: 'exist' wording (is exist -> does exist)

l10n/fr.js, l10n/fr.json
To backport to v4.0.1.
OP#3545
=> Change "G.E." to "WM" in user role selection

src/MultiSelectUsers.vue
Replace the NcMultiSelect component with the new component, NcSelect.
I will backport to v4.0.1.
OP#3528
=> Update selecting user component

src/MultiSelectUsers.vue
=> Backport: change select user component

src/SpaceMenuItem.vue
**Added group button**
**Create a workspace group button**
OP#3537
=> Harmonize hover effect for "Add a group" and "Create a workspace group" buttons

src/SpaceMenuItem.vue
=> Backport: Harmonize hover effect for "Add a group" and "Create a workspace group" buttons

.editorconfig
… actual TAB/SPACE editing rules
=> Using the tab indent style for PHP, CSS, JS and Vue in our code editor

lib/Commands/Create.php, lib/Db/SpaceMapper.php, lib/Space/SpaceManager.php, tests/Unit/Space/SpaceManagerTest.php
feat: allow to add user even if the workspace alreday exists
=> Add user as workspace manager with workspace:create command, even if the workspace already exists

lib/Controller/ConnectedGroupController.php, lib/Group/GroupBackend.php, lib/Service/Group/GroupFormatter.php
This PR is a backport from #1177
=> Backport: Users remnants show

appinfo/routes.php, lib/Controller/WorkspaceController.php, package-lock.json, package.json, src/LeftSidebar.vue, src/SpaceTable.vue, src/WorkspaceContent.vue, src/main.js, src/store/actions.js, src/store/getters.js, src/store/mutations.js
=> Backport: Load manager avatars in asynchronously with workspaces

src/SelectConnectedGroups.vue, src/SpaceTable.vue, src/UserCard.vue, src/UserTable.vue
=> Backport: Load users from users table view

lib/Controller/GroupController.php, package-lock.json, package.json, src/SelectConnectedGroups.vue
We improve the response time by implementing a debounce system before sending the request.
OP#3562
=> Reduce group search loading time

lib/Controller/GroupController.php, package-lock.json, package.json, src/SelectConnectedGroups.vue
We improve the response time by implementing a debounce system before sending the request.
OP#3562
=> Backport: Reduce group search loading time

src/SpaceDetails.vue, src/SpaceMenuItem.vue
[Capture vidéo du 2025-03-07 16-25-25.webm](https://github.com/user-attachments/assets/3f1d3d58-fa8a-4d34-b768-ddb6c8044745)
[Capture vidéo du 2025-03-07 16-26-38.webm](https://github.com/user-attachments/assets/bfe441b4-e5ad-422f-bd41-151de8f20868)
OP#3727
=> Remove duplicate user requests when navigating to a workspace or refreshing it

src/SpaceDetails.vue, src/SpaceMenuItem.vue
[Capture vidéo du 2025-03-07 16-25-25.webm](https://github.com/user-attachments/assets/3f1d3d58-fa8a-4d34-b768-ddb6c8044745)
[Capture vidéo du 2025-03-07 16-26-38.webm](https://github.com/user-attachments/assets/bfe441b4-e5ad-422f-bd41-151de8f20868)
OP#3727
backport from #1195
=> Backport: Remove duplicate user requests

lib/Db/GroupFoldersGroupsMapper.php
=> Repair display name changes for workspace groups and subgroups with PostgreSQL

lib/Db/GroupFoldersGroupsMapper.php
=> Backport: Repair display name changes for workspace groups and subgroups with PostgreSQL

src/UserTable.vue
=> User groups are sorted by alphabetically

src/UserTable.vue
=> Backport: Sort groups in user table in user table

src/MultiSelectUsers.vue
Add a setTimeOut following the advice of @smarinier 
OP#3528
=> Keep the focus on the user search input

src/MultiSelectUsers.vue
=> backport: Keep the focus on the user search input

l10n/fr.js, l10n/fr.json
=> Backport: Add upper case letters to the words ‘Workspaces’ in the French translation

src/MultiSelectUsers.vue
Scoped style for MultiSelectUsers component and added a no-options slot to display an empty dropdown.
OP#3524
=> Harmonize user select input with the added group select input

appinfo/routes.php, src/store/actions.js
Move the gid argument from the URL API to data when sending a POST request.
OP#3760
=> Allow adding groups that contain slashes

lib/Controller/ConnectedGroupController.php, lib/Controller/GroupController.php, lib/Controller/WorkspaceController.php, lib/Service/Group/ConnectedGroupsService.php, lib/Service/Group/GroupFormatter.php, lib/Service/Group/GroupsWorkspace.php, lib/Service/UserService.php, lib/Space/SpaceManager.php, src/UserTable.vue
- use Group object to use either groupid or group name
- don't add (old) local group
- fix local (old) group user menu
- replace old "str_starts_with" with static UserGroup methods
=> fix: don't show old legacy local groups as connected groups

lib/Service/Group/ConnectedGroupsService.php
=> Backport : Determine if a user belongs to an added group

lib/Controller/ConnectedGroupController.php, lib/Controller/GroupController.php, lib/Controller/WorkspaceController.php, lib/Service/Group/ConnectedGroupsService.php, lib/Service/Group/GroupFormatter.php, lib/Service/Group/GroupsWorkspace.php, lib/Service/UserService.php, lib/Space/SpaceManager.php, src/UserTable.vue
=> Backport: old subgroups in added groups section prop 2

appinfo/routes.php, l10n/en.js, l10n/fr.js, l10n/fr.json, lib/Controller/WorkspaceController.php, lib/Db/SpaceMapper.php, src/LeftSidebar.vue, src/SpaceDetails.vue, src/services/spaceService.js, src/store/actions.js, src/store/index.js, src/store/mutations.js
=> Backport: count bubble workspace

appinfo/routes.php, lib/Controller/WorkspaceController.php, lib/Db/SpaceMapper.php, src/LeftSidebar.vue, src/WorkspaceContent.vue, src/services/spaceService.js
=> Implement counter bubble for counting workspaces on the front-end

appinfo/info.xml
=> Revert "Release v4.1.0"

src/GroupDetails.vue, src/SpaceDetails.vue, src/WorkspaceContent.vue, src/store/actions.js, src/store/index.js, src/store/mutations.js
Main fix is in SpaceDetails.vue
(others are typo)
=> Fix infinite loading problem in user list

lib/Group/Admin/AdminUserGroup.php, lib/Group/User/UserGroup.php, lib/Service/Group/ConnectedGroupsService.php, lib/Service/User/UserWorkspace.php, lib/Service/UserService.php, lib/Space/SpaceManager.php
=> Backport: Ignore inconsistencies in the groups and subgroups listing for a workspace

src/GroupDetails.vue, src/SpaceDetails.vue, src/WorkspaceContent.vue, src/store/actions.js, src/store/index.js, src/store/mutations.js
=> Backport: Fix infinite loading problem in user list

lib/Controller/WorkspaceController.php, lib/Group/SubGroups/SubGroup.php
TYPO: fixing typo and wording on warning log.
=> Fixing typo and wording on warning log

src/store/actions.js
=> Remove duplicate conversion of quota string to bytes

src/MultiSelectUsers.vue
=> Reduce the number of requests needed to get a user list

lib/AppInfo/Capabilities.php, lib/Controller/PageController.php, src/App.vue, templates/index.php, tests/Unit/Controller/PageControllerTest.php
=> Display acl inherit per user

css/workspace-style.css, src/GroupDetails.vue
We had an alignment issue between different elements in the header.
=> Fix the header for the group detail page

appinfo/info.xml
=> Release v4.0.3-rc2

src/MultiSelectUsers.vue
=> Remove duplicated users found from the backend

src/MultiSelectUsers.vue
=> Backport: Remove duplicated users

appinfo/routes.php, lib/Controller/WorkspaceController.php, lib/Db/SpaceMapper.php, src/store/actions.js
We are no longer using the Groupfolders' API to set the quota.
OP#3837
=> Move setting of quota to backend

appinfo/routes.php, lib/Controller/WorkspaceController.php, lib/Db/SpaceMapper.php, src/store/actions.js
We are no longer using the Groupfolders' API to set the quota.
OP#3837
=> Backport : move set quota backend

CHANGELOG.md
=> Backport: Update CHANGELOG for v4.0.3

src/store/actions.js, src/store/mutations.js
if user count differs after loadUsers (user remnant trouble)
=> Fix infinite loading issue for users

src/store/actions.js, src/store/mutations.js
=> Backport : Fix infinite loading issue for users

src/tests/jest.setup.js
=> Add appName to jest setup

appinfo/info.xml
=> Make workspace available for Nextcloud 31

appinfo/info.xml
=> v4.0.4 rc2

src/LeftSidebar.vue, src/SelectConnectedGroups.vue, src/SpaceDetails.vue, src/SpaceMenuItem.vue
=> Replace title with name in Nextcloud components

appinfo/info.xml
=> Backport: Make workspace available for Nextcloud 31

scripts/database_checker.php
=> Backport: Database checker for workspace

lib/Controller/WorkspaceController.php, lib/Service/Group/GroupFormatter.php
count users cost in SQL and is called to many times
=> fix: optimise use of count users from groups

src/SelectConnectedGroups.vue, src/SpaceDetails.vue, src/SpaceMenuItem.vue, src/store/actions.js, src/store/mutations.js
- add connected group from "all workspace" list crash 
- may add in wrong workspace in workspace vue)
=> Add connected group from "all workspace" list crash

src/SpaceDetails.vue
I implemented a tooltip with this change.
OP#3832
=> Change quota to bubble style

src/SelectConnectedGroups.vue, src/SpaceDetails.vue, src/SpaceMenuItem.vue, src/store/actions.js, src/store/mutations.js
=> Bacport: Can't add connected group from workspaces list/1303/main

Makefile, composer.json, composer.lock, lib/AppInfo/Capabilities.php, lib/Controller/ConnectedGroupController.php, lib/ResponseDefinitions.php
- Add nextcloud/openapi generator
- Add comments in capabilities (required by generator)
- Add ResponseDefinitions -> will be necessary for each definitions implied with API calls (payload and responses)
- Comment first internal API (enough for all api calls ?)
=> feat: make openapi

composer.lock, lib/Controller/WorkspaceApiOcsController.php, lib/ResponseDefinitions.php, lib/Space/SpaceManager.php, tests/Unit/Controller/WorkspaceApiOcsControllerTest.php, tests/Unit/Space/SpaceManagerTest.php
=> Retrieve groups from a workspace using OCS API

lib/Controller/WorkspaceApiOcsController.php, lib/Space/SpaceManager.php, tests/Unit/Controller/WorkspaceApiOcsControllerTest.php, tests/Unit/Space/SpaceManagerTest.php
=> Delete users from a workspace using OCS API

lib/Controller/WorkspaceApiOcsController.php, lib/Space/SpaceManager.php, tests/Unit/Controller/WorkspaceApiOcsControllerTest.php, tests/Unit/Space/SpaceManagerTest.php
=> Set user as Workspace Manager in workspace using OCS API

lib/Controller/WorkspaceApiOcsController.php, lib/Space/SpaceManager.php, tests/Unit/Controller/WorkspaceApiOcsControllerTest.php, tests/Unit/Space/SpaceManagerTest.php
=> Remove user as workspace manager with ocs api

.gitignore, lib/Controller/WorkspaceApiOcsController.php, openapi.json, scripts/api-test.conf.sample, scripts/api-test.js
- all returns are DataResponse
- comments for openapi.json
- fix route from removeUsersFromGroup
- check non-existing group in removeUsersFromGroup
- fix route from addUsersToGroup
- check non-existing space in addUsersToGroup
- check non-existing group in addUsersToGroup
- scripts/api-test.js up-to-date with last api calls
- api-test.conf.sample with 'users' sample
=> comment for openapi and update api-test.js

lib/Controller/WorkspaceApiOcsController.php, lib/Space/SpaceManager.php, tests/Unit/Controller/WorkspaceApiOcsControllerTest.php
=> Create a new OCS API endpoint to retrieve users from a workspace

lib/Space/SpaceManager.php, tests/Unit/Space/SpaceManagerTest.php
=> Remove users key from getting workspaces

lib/Controller/WorkspaceApiOcsController.php, lib/Service/Group/GroupsWorkspaceService.php, tests/Unit/Controller/WorkspaceApiOcsControllerTest.php
=> Implement a new OCS API endpoint for removing a subgroup

appinfo/info.xml
=> v4.1.0-dev3

src/AddUsersTabs.vue, src/UserCard.vue
=> Enable checkbox when adding a user who's not a WM

lib/AppInfo/Application.php
=> Backport:  Take added groups into account in ACLs for stable4.0

l10n/en.js, l10n/fr.js, l10n/fr.json, src/GroupDetails.vue
=> Update French translation on subgroup deletion

package-lock.json, src/SpaceDetails.vue, webpack.config.js
=> Use a specific component for icons

lib/Controller/GroupController.php, lib/Events/UserRemovedFromGroupEvent.php
=> Add event when removing a user from the group

lib/AppInfo/Application.php, lib/Attributes/NoSpecialChar.php, lib/Controller/WorkspaceApiOcsController.php, lib/Middleware/NoSpecialCharMiddleware.php, lib/Space/SpaceManager.php
OP#4353
OP#4354
OP#4356
OP#4357
OP#4358
RM#3475
RM#3473
=> Add attribute to forbid special characters
