arawa/workspace

lib/Service/WorkspaceService.php
src/SelectUsers.vue

From select users interface, we can search users suit email, name or uid.
In this demo, I searched for users, in order, by uid, name and email.
@LivOriona what do you think ?

Searching users by email, name or uid

---

lib/Controller/GroupController.php
src/store/actions.js

I unintentionally deleted the spaceId as argument to create a group.
It's okay for you @LivOriona ?

fix(PHP, Vue): A user who is a GE can create groups

---

Makefile
appinfo/info.xml
composer.lock
package-lock.json

I mistake on the release. I took into account the number of fix in the minor release
I updated the makefile to take into account the CHANGELOG.md and .enslintr.js files to ignore for the build
I updated the lock files too

chore(): Downgrade the release to 1.2.0 and our app is compatible for NC23

---

l10n/en.js
l10n/fr.js
l10n/fr.json
src/SpaceDetails.vue
src/store/actions.js

I fix an issue related to the creating of a group.

Prevent the duplication of group

---

src/SpaceDetails.vue

I removed the space id between brackets in the title.

Remove the space id in the title

---

l10n/cs.js
l10n/cs.json
l10n/en.js
l10n/fr.js
l10n/fr.json
src/RemoveSpace.vue

I changed the translation "space" to "workspace" in the RemoveSpace.vue.
@Clementine46 and @dorianne-arawa , it's okay for you ?

Change the translation in workspace

---

src/Home.vue
src/services/groupfoldersService.js
src/services/spaceService.js
src/store/actions.js

Add 5s to notifications in a few places

---

CHANGELOG.md
docs/dev/CHANGELOG.md
src/SpaceDetails.vue

This fix is to PR #801, there was an error caused by wrong variable name ShowSpaceMenu instead of ShowDelWorkspaceModal. This resulted in an issue with space removal, when clicking on "Delete Worskapce" menu item the modal window didn't open.

fix(vue): remove not used variable and replace by a proper one

---

lib/Controller/GroupController.php
src/GroupDetails.vue
src/SpaceDetails.vue
src/store/actions.js

Now, when we will rename one space, all groups (even WM- and U-) will be changed with the new space name.
If one group is renamed, it will be suffixed and prefixed with G- and the space name.
@acdmft can you review and test my code, please ?
This PR will be backported to stable3.0 .

fix(Vue,Php): Rename the groups with the spacename

---

CHANGELOG.md
appinfo/info.xml
lib/Controller/WorkspaceController.php
lib/Migration/ChangeGroupnamesV300.php
lib/Migration/FixMigrationToV300.php
lib/Service/Group/WorkspaceManagerGroup.php
lib/Upgrade/UpgradeFixV300V301.php
lib/Upgrade/UpgradeV300.php

It's a backport from this PR https://github.com/arawa/workspace/pull/843/ for the stable3.0 branch

Backport/update to 3.0.0/stable3.0

---

css/workspace-style.css
src/GroupMenuItem.vue
src/LeftSidebar.vue
src/SpaceMenuItem.vue

This PR split the Space item from the LeftSidebar in 2 components : 
- SpaceMenuItem : It's the space item in the LeftSidebar where we list a space and its groups.
- GroupMenuItem : It's the group item in the sub-menu of a space.

Create spaceitem and groupitem components

---

CHANGELOG.md
docs/dev/CHANGELOG.md
src/GroupDetails.vue

This PR is intended to fix a minor bug of the UI: wWhen trying to rename a user group and there is an error message the modal window continue to be present on the page. This is fixed with adding ref to corresponding component and then call 'this.$refs.ncAction.opened=false'.

hide modal window menu when there is an error message 

---

lib/Service/WorkspaceService.php

This commit PR duplicate users when we search them with the `apps/workspace/api/autoComplete/:term/:spaceId` api/rest.

Prevent duplicate users_oidc

---

CHANGELOG.md
src/SelectUsers.vue

I deleted an old code which deletes an user as soon as him/her is added to another a subgroup.
Resolve this issue: https://github.com/arawa/workspace/issues/901
@dorianne-arawa we must test this fix.

Don't remove an user from a subgroup

---

README.md
appinfo/info.xml

It's a backport from #911 for the `stable3.0` branch.

Backport/inform users refresh browser/911/stable3.0

---

appinfo/routes.php

I added the `'postfix' => 'catchall'` to make the distinction between the two page#index routes.

Make the distinction between the page#index

---

lib/Controller/GroupController.php
lib/Controller/WorkspaceController.php
lib/Service/UserService.php

I have checked incorrectly whether an user is a space manager of another space.

Check if an user is a space manager

---

src/SpaceDetails.vue

I added an arrow for the creating group field.
Screenshot
@dorianne-arawa & @Clementine46 : Can you confirm me if it's okay for you ?

Add an arrow in a field

---

lib/Controller/GroupController.php
src/SpaceDetails.vue

When we rename a space from plural to single (or inversely) all groups are bad renamed.

fix(vue,php): Problem about renaming a space

---

lib/Controller/GroupController.php
src/SpaceDetails.vue

When we rename a space from plural to single (or inversely) all groups are bad renamed.
It's a backport from #893

Backport: Problem about renaming a space

---

src/SpaceDetails.vue

I added an arrow for the creating group field.
It's a backport from #900

Backport: Add an arrow in a field

---

lib/Controller/GroupController.php
lib/Controller/WorkspaceController.php
lib/Service/UserService.php

I have checked incorrectly whether an user is a space manager of another space.
It's a backport from #915

Backport: Check if an user is a space manager

---

lib/Service/WorkspaceService.php
lib/Share/Group/GroupMembersOnlyChecker.php
lib/Share/Group/ShareMembersOnlyFilter.php

Limit the search to members of the same group except for specific groups.
I splited the code in 2 classes :
- GroupMembersOnlyChecker : To check if the checkbox for the "Allow apps to use the Share API" and check if groups are listed from the multiselect.
- ShareMembersOnlyFilter : to get the members only the same group or excepted a few groups from the multiselect.
Return users with common groups. Except users belonging to groups listed in the drop-down list (`Settings > Share > Restrict users to only share with users in their groups > Ingore the following groups when cheking group membership`).

backport: Limit the search to members

---

CHANGELOG.md
appinfo/info.xml

Normally, this release should have been 4.0.0 from a dev point of view. We adapted it for marketing purposes.

Release 3.2.0 and available for nc29

---

lib/Controller/WorkspaceController.php
src/WorkspaceContent.vue

missing added_groups in JSON and JS

---

appinfo/info.xml

WorkSpace must be considered as dav types, in order to boot on dav rquests

WorkSpace is "dav" type

---

lib/AppInfo/Application.php
lib/Middleware/IsGeneralManagerMiddleware.php

- register IsGeneralManagerMiddleware
- return good type with afterException (JSONresponse)

registering IsGeneralManagerMiddleware

---

lib/Migration/FixMigrationToV300.php
lib/Service/Group/GroupsWorkspace.php

- use default values
- use same values in migration

Use default values when prefix options are missing

---

lib/AppInfo/Application.php
lib/AppInfo/Capabilities.php
lib/Controller/WorkspaceController.php
src/services/groupfoldersService.js
src/store/actions.js

We expose the app version and is enabled.
- verb: GET
- URI: /ocs/v2.php/cloud/capabilities
- Header: OCS-APIRequest:true
- Header: Accept:application/json
Respond to this need : https://github.com/arawa/workspace/issues/1040.

Expose our capabilities

---

appinfo/info.xml

It's a backport from #958 for the  `stable3.2.` branch.

Update user docs appstore side

---

lib/Controller/WorkspaceController.php

It's possible for a group not to exist, but still to be attached to a groupfolder.
This change allows for this issue.

Check if the group already exist before rendering

---

appinfo/routes.php
lib/Controller/GroupController.php
lib/Space/SpaceManager.php
src/App.vue
src/services/spaceService.js
src/store/actions.js

Fixes the issue where "Password confirmation is required" by allowing groups to be attached without needing password confirmation.

Create an API for attaching a group to a workspace

---

appinfo/routes.php
lib/Controller/GroupController.php
lib/Controller/WorkspaceController.php
lib/Group/GroupBackend.php
lib/Service/Group/GroupFormatter.php
lib/Service/WorkspaceService.php
src/GroupDetails.vue
src/GroupMenuItem.vue
src/LoadingUsers.vue
src/SelectUsers.vue
src/SpaceDetails.vue
src/SpaceMenuItem.vue
src/SpaceTable.vue
src/UserTable.vue
src/WorkspaceContent.vue
src/services/spaceService.js
src/store/actions.js
src/store/getters.js
src/store/index.js
src/store/mutations.js

Improve performance workspace listing

---

src/SelectUsers.vue

When adding a user from a subgroup, the role checkbox should be disabled for existing user.

Disable checkbox for existing users

---

appinfo/routes.php
lib/Controller/WorkspaceController.php
src/services/groupfoldersService.js
src/tests/unit/groupfoldersService.test.js

We have implemented the IBootstrap interface in the Application class. This means that Middleware is registered differently, and the destroy() method in the WorkspaceController could not work without this change.

API for workspace deletion

---

lib/Db/GroupFoldersGroupsMapper.php
lib/Service/Group/ConnectedGroupsService.php

This fix resolves an issue with displaying workspaces, which could trigger an error notification. A user can belong to multiple groups, and this change ensures that all groups are considered.
Special thank to @smarinier :pray:

Find all added groups instead of just one

---

lib/Group/GroupBackend.php
lib/Service/Group/GroupFormatter.php
tests/Unit/Space/SpaceManagerTest.php

If a connected group contains disabled users, we have to hide them.
Here we have 18 users...
With 2 disabled users.
And they don't count towards the workspace.
I will backport this PR for the milestone v4.0.1.
OP#3549

Hide disabled users from connected groups

---

lib/Group/GroupBackend.php
lib/Service/Group/GroupFormatter.php
tests/Unit/Space/SpaceManagerTest.php

Backport: hide disabled users

---

README.md

Backport: Remove incompatibility groupfolders message

---

lib/Controller/ConnectedGroupController.php
lib/Service/Group/ConnectedGroupsService.php
lib/Service/User/UserFormatter.php
lib/Service/UserService.php
lib/Users/UserFormatter.php
tests/Unit/Service/UserServiceTest.php

Backport: user counter when removing user

---

lib/Service/Group/ConnectedGroupsService.php

There is a confusion between `$group->getGID()` and the `$group->getGid()`. The `getGid()` method is used to retrieve the `gid` property from the Connected Group entity, while the `getGID()` method is from the IGroup class.

Listing connected groups

---

appinfo/routes.php
lib/Controller/WorkspaceController.php
package-lock.json
package.json
src/LeftSidebar.vue
src/SpaceTable.vue
src/WorkspaceContent.vue
src/main.js
src/store/actions.js
src/store/getters.js
src/store/mutations.js

Use VueLazyComponent and delay draw of wm admins for workspaces list

Load manager avatars in asynchronously with workspaces

---

l10n/fr.js
l10n/fr.json

Tous les workspaces -> Tous les Workspaces

Add upper case letters to the words ‘Workspaces’ in the French translation

---

appinfo/routes.php
src/store/actions.js

Move the gid argument from the URL API to data when sending a POST request.
OP#3760

Backport: connected groups with slashs

---

src/MultiSelectUsers.vue

Scoped style for MultiSelectUsers component and added a no-options slot to display an empty dropdown.
OP#3524

Backport: Harmonize user select input with the added group select input

---

lib/Group/Admin/AdminUserGroup.php
lib/Group/User/UserGroup.php
lib/Service/Group/ConnectedGroupsService.php
lib/Service/User/UserWorkspace.php
lib/Service/UserService.php
lib/Space/SpaceManager.php

if a groupfolder_group was deleted, especially as "connected group", then it crashes /spaces/

Ignore inconsistencies in the groups and subgroups listing for a workspace

---

css/workspace-style.css
src/AddUsersTabs.vue
src/GroupDetails.vue
src/LeftSidebar.vue
src/MenuItemSelector.vue
src/SpaceDetails.vue

Story #3869
OK 3. menu latéral de gauche : remettre en place le système de sélection des WSP du menu de gauche (pour afficher le WSP "en cours" et ses sous-groupes (wsp et ajoutés) associés)
OK 4. menu latéral de gauche : le bouton "all workspaces" est trop petit + son rectangle bleu est coupé en bas
OK 5. menu latéral de gauche : le bouton "create a workspace" parait petit
OK 6. menu latéral de gauche : les icônes des groupes G- et ajoutés ne sont pas du tout alignées avec leur texte correspondant (le displayName du groupe)
OK 8. dans la page d'un WSP, en cliquant sur le bouton "+" en haut à droite : les icônes de "create a workspace group" et "add a group" ne sont pas alignées par rapport aux texte
OK 9. fenêtre modale d'ajout de users  : la fenêtre "add a user" est très grande + coupée …

Redesign after updating nextcloud/vue 8.x

---

lib/Helper/GroupfolderHelper.php

returns now null (instead of false) on missing groupfolder
All tests in application are based on false with === (or !==)

fix: #3874 GroupFolder changed getFolder 

---

lib/Controller/PageController.php
lib/Controller/WorkspaceApiOcsController.php
lib/Db/SpaceMapper.php
lib/Group/SubGroups/SubGroup.php
lib/ResponseDefinitions.php
lib/Space/SpaceManager.php
openapi.json
scripts/api-test.conf.sample
scripts/api-test.js
scripts/package.json
tests/Unit/Controller/WorkspaceApiOcsControllerTest.php
tests/Unit/Group/SubGroups/SubGroupTest.php
tests/Unit/Space/SpaceManagerTest.php

- /space/{id} ne renvoie pas 404 sur workspace inexistant
- openapi doc pour PATCH /space/{id}
- api/v1/nimportequoi renvoie OK
- Create a new workspace : pas /spaces mais /space
- Create a new workspace : pas "spacename" mais "name" (comme le champ qu'on obtient en get)
- Create a new workspace : ajout du retour 409 (conflict)
- openapi doc pour addUserAsWorkspaceManager
- openapi doc pour removeUserAsWorkspaceManager
- le DELETE workspace a un problème (m'a effacé le groupfolder mais pas le workspace)
- Params en niveau params{} dans edit
- Edit avec même nom crash
- Create subgroup /groups -> /group
- Create subgroup param "name" et pas "groupname"
- Ajouter openapi.json
- AddUserWM et removeUserWM -> n'existe pas doc 404
- scripts/api-test.js run OCS api scenario

- various OCS API fixes & script api-test.js

---

lib/Exceptions/MountProviderFunctionException.php
lib/Helper/MountProviderHelper.php
lib/Space/SpaceManager.php
scripts/database_checker.php
tests/Unit/Space/SpaceManagerTest.php

OP#4199
The code to delete groupfolders after updating the workspace app or running a script :
```php
/** @var \OCP\Files\Folder $folder */
$folder = $this->rootFolderTest->get('__groupfolders');
$groupfolderPath = $folder->getPath();
$folders = $folder->getDirectoryListing();
$pathes = array_map(fn ($node) => $node->getPath(), $folders);
$groupfolders = $this->folderHelper->getAllFolders();
$folderIds = array_values(array_map(fn ($groupfolder) => $groupfolder['id'], $groupfolders));
$folders = array_filter($pathes, fn ($path) => !str_ends_with($path, 'versions') && !str_ends_with($path, 'trash'));
$idsWithPath = array_map(fn ($id) => "{$groupfolderPath}/{$id}", $folderIds);
$foldersShadow = array_values(array_diff($folders, $idsWithPath));
foreach ($foldersShadow as $folderPath) { …
```

Remove files from groupfolders on the web server
